# Generated by Django 5.0.6 on 2024-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commonbase", "0002_review_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
